=== qqdiguo/vizstack/share/schema/displayconfig.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.hp.com"
xmlns="http://www.hp.com"
elementFormDefault="qualified" >

<xs:element name="displayconfig">
	<xs:complexType>
		<xs:sequence>
			<!-- Mandatory name comes first. This is the name of the model. -->
			<xs:element name="model" type="xs:string" />

			<!-- Next comes vendor -->
			<xs:element name="vendor" type="xs:string" />

			<!-- 

			The type of input this display device takes by default. 
			If the device connectes using a digital interface, then use "digital". All flat panels will be by default digital.
			Digital interfaces are connected using either DVI-D or "DisplayPort". Avoid usage of DVI-I cables. This may make the GPU
			switch to using analog signals.
			If the device connects using a VGA cable, use "analog". All CRT displays are analog.
			-->
			<xs:element name="input" > 
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="digital" />
						<xs:enumeration value="analog" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>

			<!-- 

			If you can get the EDID for this device, then use it here. Else be prepared to specify
			modelines

			-->
			<xs:element name="edid" minOccurs="0" maxOccurs="1" type="xs:string" />
			<xs:element name="edidBytes" minOccurs="0" maxOccurs="1" type="xs:string" />

			<xs:element name="hsync" minOccurs="0" maxOccurs="1" > <!-- If EDID is not specified, the sync value will be used from this -->
				<xs:complexType>
					<xs:sequence>
						<xs:element name="min" type="xs:string" />
						<xs:element name="max" type="xs:string" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>

			<xs:element name="vrefresh" minOccurs="0" maxOccurs="1" > <!-- If EDID is not specified, the sync value will be used from this -->
				<xs:complexType>
					<xs:sequence>
						<xs:element name="min" type="xs:string" />
						<xs:element name="max" type="xs:string" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>

			<xs:element name="default_mode" type="xs:string" /> <!-- The default mode to choose if none is specified. Must be in the list below -->

			<xs:element name="mode" minOccurs="0" maxOccurs="unbounded" >
				<xs:complexType>
					<xs:sequence>
						<xs:element name="type" type="xs:string" />
						<xs:element name="alias" type="xs:string" minOccurs="1" maxOccurs="unbounded" />
						<xs:element name="width" type="xs:nonNegativeInteger" />
						<xs:element name="height" type="xs:nonNegativeInteger" />
						<xs:element name="refresh" type="xs:nonNegativeInteger" />
						<xs:element name="value" type="xs:string" minOccurs="0" maxOccurs="1" /> <!-- value depends on 'type'. Can be a modeline or empty at this point -->
					</xs:sequence>
				</xs:complexType>
			</xs:element>

		</xs:sequence>
	</xs:complexType>
</xs:element>

</xs:schema>

=== qqdiguo/vizstack/trunk/share/templates/displays/generic-stereo-CRT.xml
<?xml version="1.0" ?>

<displayconfig 
 xmlns="http://www.hp.com"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.hp.com /opt/vizstack/share/schema/displayconfig.xsd" >
	<model>GenericStereoCRT</model>
	<vendor>generic</vendor>
	<input>analog</input>
	<hsync>
		<min>30</min>
		<max>150</max>
	</hsync>
	<vrefresh>
		<min>50</min>
		<max>120</max>
	</vrefresh>
	<default_mode>1280x1024_110</default_mode>
	<mode>
		<type>modeline</type>
		<alias>1280x1024_110</alias>
		<width>1280</width>
		<height>1024</height>
		<refresh>110</refresh>
		<value>211.22  1280 1376 1520 1760  1024 1025 1028 1091 -HSync +Vsync</value> <!-- GTF generated modeline !-->
	</mode>
</displayconfig>

=== qqdiguo/vizstack/trunk/share/templates/displays/LPL-LPL.xml
<?xml version="1.0" ?>

<!--

LPL is Shree's Laptop's (DV 2000 series) display

According to the EDID, manufacturer is "LPL", and monitor name is "LPL" too !

-->

<displayconfig 
 xmlns="http://www.hp.com"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.hp.com /opt/vizstack/share/schema/displayconfig.xsd" >
	<model>DV 2000</model>
	<vendor>LPL</vendor>
	<input>digital</input>
	<edid>/opt/vizstack/share/templates/displays/edids/LPL-LPL.bin</edid>
	<default_mode>1280x800_60</default_mode>
	<mode>
		<type>edid</type>
		<alias>1280x800_60</alias>
		<alias>1280x800</alias>
		<width>1280</width>
		<height>800</height>
		<refresh>60</refresh>
	</mode>
</displayconfig>

=== qqdiguo/vizstack/share/templates/displays/HP-LP3065.xml
<?xml version="1.0" ?>

<!--

LP3065 is HP's top-end 30" LCD monitor (at the time of writing this).

The LP 3065 supports resolutions upto 2560x1600 @ 60Hz.

-->

<displayconfig 
 xmlns="http://www.hp.com"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.hp.com /opt/vizstack/share/schema/displayconfig.xsd" >
	<model>LP3065</model>
	<vendor>HP</vendor>
	<input>digital</input>
	<edid>/opt/vizstack/share/templates/displays/edids/HP-LP3065.bin</edid>
	<default_mode>2560x1600_60</default_mode>
	<mode>
		<type>edid</type>
		<alias>2560x1600_60</alias>
		<alias>2560x1600</alias>
		<width>2560</width>
		<height>1600</height>
		<refresh>60</refresh>
	</mode>
	<mode>
		<type>edid</type>
		<alias>1280x800_60</alias>
		<alias>1280x800</alias>
		<width>1280</width>
		<height>800</height>
		<refresh>60</refresh>
	</mode>
</displayconfig>
